
project_id = "yrafjktkkspcptkcaowj"

[functions.quotes-api]
verify_jwt = false

[functions.external-quote-submissions]
verify_jwt = false

[functions.process-evidence-image]
verify_jwt = false

[functions.autofill-quote-metadata]
verify_jwt = true

[functions.cq-generate-quotes]
verify_jwt = true
