
export interface Quote {
  id: string,
  text: string,
  author: string,
  date: string,
  topics: string[],
  theme: string,
  source?: string,
  evidenceImage?: string,
  sourceUrl?: string,
  sourcePublicationDate?: string,
  originalLanguage?: string,
  originalText?: string,
  context?: string,
  historicalContext?: string,
  keywords?: string[],
  citationAPA?: string,
  citationMLA?: string,
  citationChicago?: string,
  exportFormats?: {
    json?: boolean,
    csv?: boolean,
    cff?: boolean
  },
  shareCount?: number,
  variations?: any[],
  crossReferencedQuotes?: any[],
  ocrExtractedText?: string,
  ocrConfidenceScore?: number,
  originalManuscriptReference?: string,
  attributionStatus?: string,
  translator?: string,
  impact?: string,
  citedBy?: {
    siteName: string,
    siteUrl: string,
    embedDate: string
  }[],
  translations?: {
    fr?: {
      text: string,
      source?: string
    }
  }
}

export const quotes: Quote[] = [
  {
    id: "1",
    text: "The only way to do great work is to love what you do.",
    author: "Steve Jobs",
    date: "2005-06-12",
    topics: ["business", "success"],
    theme: "passion",
    source: "Stanford Commencement Address",
  },
  {
    id: "2",
    text: "Innovation distinguishes between a leader and a follower.",
    author: "Steve Jobs",
    date: "1996-01-01",
    topics: ["business", "innovation"],
    theme: "leadership",
  },
  {
    id: "3",
    text: "The future belongs to those who believe in the beauty of their dreams.",
    author: "Eleanor Roosevelt",
    date: "1933-01-01",
    topics: ["inspirational", "dreams"],
    theme: "hope",
  },
  {
    id: "4",
    text: "The best and most beautiful things in the world cannot be seen or even touched - they must be felt with the heart.",
    author: "Helen Keller",
    date: "1920-01-01",
    topics: ["love", "beauty"],
    theme: "emotion",
  },
  {
    id: "5",
    text: "Strive not to be a success, but rather to be of value.",
    author: "Albert Einstein",
    date: "1949-01-01",
    topics: ["success", "value"],
    theme: "purpose",
  },
  {
    id: "6",
    text: "The mind is everything. What you think you become.",
    author: "Buddha",
    date: "-500-01-01",
    topics: ["mind", "philosophy"],
    theme: "mindset",
  },
  {
    id: "7",
    text: "Two things are infinite: the universe and human stupidity; and I'm not sure about the universe.",
    author: "Albert Einstein",
    date: "1922-01-01",
    topics: ["humor", "science"],
    theme: "humor",
  },
  {
    id: "8",
    text: "Be the change that you wish to see in the world.",
    author: "Mahatma Gandhi",
    date: "1913-01-01",
    topics: ["change", "inspirational"],
    theme: "activism",
  },
  {
    id: "9",
    text: "Darkness cannot drive out darkness: only light can do that. Hate cannot drive out hate: only love can do that.",
    author: "Martin Luther King Jr.",
    date: "1963-01-01",
    topics: ["love", "peace"],
    theme: "unity",
  },
  {
    id: "10",
    text: "The only limit to our realization of tomorrow will be our doubts of today.",
    author: "Franklin D. Roosevelt",
    date: "1939-01-01",
    topics: ["future", "inspirational"],
    theme: "optimism",
  },
  {
    id: "11",
    text: "It is our choices, Harry, that show what we truly are, far more than our abilities.",
    author: "J.K. Rowling",
    date: "1999-01-01",
    topics: ["choices", "character"],
    theme: "integrity",
    source: "Harry Potter and the Chamber of Secrets"
  },
  {
    id: "12",
    text: "The journey of a thousand miles begins with one step.",
    author: "Lao Tzu",
    date: "-0600-01-01",
    topics: ["inspirational", "perseverance"],
    theme: "determination",
  },
  {
    id: "13",
    text: "Life is what happens when you're busy making other plans.",
    author: "John Lennon",
    date: "1980-01-01",
    topics: ["life", "perspective"],
    theme: "reality",
  },
  {
    id: "14",
    text: "The greatest glory in living lies not in never falling, but in rising every time we fall.",
    author: "Nelson Mandela",
    date: "2000-01-01",
    topics: ["inspirational", "perseverance"],
    theme: "resilience",
  },
  {
    id: "15",
    text: "Do not go where the path may lead, go instead where there is no path and leave a trail.",
    author: "Ralph Waldo Emerson",
    date: "1841-01-01",
    topics: ["leadership", "individuality"],
    theme: "innovation",
  },
  {
    id: "16",
    text: "The best way to predict the future is to create it.",
    author: "Peter Drucker",
    date: "1963-01-01",
    topics: ["future", "innovation"],
    theme: "proactivity",
  },
  {
    id: "17",
    text: "Happiness is not something readymade. It comes from your own actions.",
    author: "Dalai Lama",
    date: "1998-01-01",
    topics: ["happiness", "philosophy"],
    theme: "mindfulness",
  },
  {
    id: "18",
    text: "The only true wisdom is in knowing you know nothing.",
    author: "Socrates",
    date: "-399-01-01",
    topics: ["wisdom", "philosophy"],
    theme: "humility",
  },
   {
    id: "19",
    text: "I have always depended on the kindness of strangers.",
    author: "Tennessee Williams",
    date: "1947-01-01",
    topics: ["kindness", "society"],
    theme: "vulnerability",
    source: "A Streetcar Named Desire"
  },
  {
    id: "20",
    text: "That it will never come again is what makes life so sweet.",
    author: "Emily Dickinson",
    date: "1864-01-01",
    topics: ["life", "perspective"],
    theme: "transience",
  },
  {
    id: "21",
    text: "Don't cry because it's over, smile because it happened.",
    author: "Dr. Seuss",
    date: "1956-01-01",
    topics: ["life", "happiness"],
    theme: "gratitude",
  },
  {
    id: "22",
    text: "To be or not to be, that is the question.",
    author: "William Shakespeare",
    date: "1603-01-01",
    topics: ["life", "philosophy"],
    theme: "existence",
    source: "Hamlet"
  },
  {
    id: "23",
    text: "The unexamined life is not worth living.",
    author: "Socrates",
    date: "-399-01-01",
    topics: ["life", "philosophy"],
    theme: "introspection",
  },
  {
    id: "24",
    text: "The only thing necessary for the triumph of evil is for good men to do nothing.",
    author: "Edmund Burke",
    date: "1770-01-01",
    topics: ["evil", "society"],
    theme: "responsibility",
  },
  {
    id: "25",
    text: "The greatest wealth is to live content with little.",
    author: "Plato",
    date: "-380-01-01",
    topics: ["wealth", "philosophy"],
    theme: "contentment",
  },
  {
    id: "26",
    text: "Where there is love there is life.",
    author: "Mahatma Gandhi",
    date: "1931-01-01",
    topics: ["love", "life"],
    theme: "vitality",
  },
  {
    id: "27",
    text: "We are all in the gutter, but some of us are looking at the stars.",
    author: "Oscar Wilde",
    date: "1897-01-01",
    topics: ["hope", "perspective"],
    theme: "aspiration",
    source: "Lady Windermere's Fan"
  },
  {
    id: "28",
    text: "The truth will set you free, but first it will piss you off.",
    author: "Joe Klaas",
    date: "1994-01-01",
    topics: ["truth", "freedom"],
    theme: "honesty",
  },
  {
    id: "29",
    text: "Not all those who wander are lost.",
    author: "J.R.R. Tolkien",
    date: "1954-01-01",
    topics: ["travel", "individuality"],
    theme: "exploration",
    source: "The Fellowship of the Ring"
  },
  {
    id: "30",
    text: "The best revenge is massive success.",
    author: "Frank Sinatra",
    date: "1964-01-01",
    topics: ["success", "revenge"],
    theme: "achievement",
  },
  {
    id: "31",
    text: "If you can't explain it to a six year old, you don't understand it yourself.",
    author: "Albert Einstein",
    date: "1930-01-01",
    topics: ["understanding", "simplicity"],
    theme: "clarity",
  },
  {
    id: "32",
    text: "I would like to die on Mars. Just not on impact.",
    author: "Elon Musk",
    date: "2015-01-01",
    topics: ["humor", "space"],
    theme: "ambition",
  }
]
