
export interface Quote {
  id: string,
  text: string,
  author: string,
  date: string,
  topics: string[],
  theme: string,
  source?: string,
  evidenceImage?: string,
  translations?: {
    fr?: {
      text: string,
      source?: string
    }
  }
}

export const quotes: Quote[] = [
  {
    id: "1",
    text: "The only way to do great work is to love what you do.",
    author: "Steve Jobs",
    date: "2005-06-12",
    topics: ["business", "success"],
    theme: "passion",
    source: "Stanford Commencement Address",
  },
  {
    id: "2",
    text: "Innovation distinguishes between a leader and a follower.",
    author: "Steve Jobs",
    date: "1996-01-01",
    topics: ["business", "innovation"],
    theme: "leadership",
  },
  {
    id: "3",
    text: "The future belongs to those who believe in the beauty of their dreams.",
    author: "Eleanor Roosevelt",
    date: "1933-01-01",
    topics: ["inspirational", "dreams"],
    theme: "hope",
  },
  {
    id: "4",
    text: "The best and most beautiful things in the world cannot be seen or even touched - they must be felt with the heart.",
    author: "Helen Keller",
    date: "1920-01-01",
    topics: ["love", "beauty"],
    theme: "emotion",
  },
  {
    id: "5",
    text: "Strive not to be a success, but rather to be of value.",
    author: "Albert Einstein",
    date: "1949-01-01",
    topics: ["success", "value"],
    theme: "purpose",
  },
  {
    id: "6",
    text: "The mind is everything. What you think you become.",
    author: "Buddha",
    date: "-500-01-01",
    topics: ["mind", "philosophy"],
    theme: "mindset",
  },
  {
    id: "7",
    text: "Two things are infinite: the universe and human stupidity; and I'm not sure about the universe.",
    author: "Albert Einstein",
    date: "1922-01-01",
    topics: ["humor", "science"],
    theme: "humor",
  },
  {
    id: "8",
    text: "Be the change that you wish to see in the world.",
    author: "Mahatma Gandhi",
    date: "1913-01-01",
    topics: ["change", "inspirational"],
    theme: "activism",
  },
  {
    id: "9",
    text: "Darkness cannot drive out darkness: only light can do that. Hate cannot drive out hate: only love can do that.",
    author: "Martin Luther King Jr.",
    date: "1963-01-01",
    topics: ["love", "peace"],
    theme: "unity",
  },
  {
    id: "10",
    text: "The only limit to our realization of tomorrow will be our doubts of today.",
    author: "Franklin D. Roosevelt",
    date: "1939-01-01",
    topics: ["future", "inspirational"],
    theme: "optimism",
  },
  {
    id: "11",
    text: "It is our choices, Harry, that show what we truly are, far more than our abilities.",
    author: "J.K. Rowling",
    date: "1999-01-01",
    topics: ["choices", "character"],
    theme: "integrity",
    source: "Harry Potter and the Chamber of Secrets"
  },
  {
    id: "12",
    text: "The journey of a thousand miles begins with one step.",
    author: "Lao Tzu",
    date: "-0600-01-01",
    topics: ["inspirational", "perseverance"],
    theme: "determination",
  },
  {
    id: "13",
    text: "Life is what happens when you're busy making other plans.",
    author: "John Lennon",
    date: "1980-01-01",
    topics: ["life", "perspective"],
    theme: "reality",
  },
  {
    id: "14",
    text: "The greatest glory in living lies not in never falling, but in rising every time we fall.",
    author: "Nelson Mandela",
    date: "2000-01-01",
    topics: ["inspirational", "perseverance"],
    theme: "resilience",
  },
  {
    id: "15",
    text: "Do not go where the path may lead, go instead where there is no path and leave a trail.",
    author: "Ralph Waldo Emerson",
    date: "1841-01-01",
    topics: ["leadership", "individuality"],
    theme: "innovation",
  },
  {
    id: "16",
    text: "The best way to predict the future is to create it.",
    author: "Peter Drucker",
    date: "1963-01-01",
    topics: ["future", "innovation"],
    theme: "proactivity",
  },
  {
    id: "17",
    text: "Happiness is not something readymade. It comes from your own actions.",
    author: "Dalai Lama",
    date: "1998-01-01",
    topics: ["happiness", "philosophy"],
    theme: "mindfulness",
  },
  {
    id: "18",
    text: "The only true wisdom is in knowing you know nothing.",
    author: "Socrates",
    date: "-399-01-01",
    topics: ["wisdom", "philosophy"],
    theme: "humility",
  },
   {
    id: "19",
    text: "I have always depended on the kindness of strangers.",
    author: "Tennessee Williams",
    date: "1947-01-01",
    topics: ["kindness", "society"],
    theme: "vulnerability",
    source: "A Streetcar Named Desire"
  },
  {
    id: "20",
    text: "That it will never come again is what makes life so sweet.",
    author: "Emily Dickinson",
    date: "1864-01-01",
    topics: ["life", "perspective"],
    theme: "transience",
  },
  {
    id: "21",
    text: "Don't cry because it's over, smile because it happened.",
    author: "Dr. Seuss",
    date: "1956-01-01",
    topics: ["life", "happiness"],
    theme: "gratitude",
  },
  {
    id: "22",
    text: "To be or not to be, that is the question.",
    author: "William Shakespeare",
    date: "1603-01-01",
    topics: ["life", "philosophy"],
    theme: "existence",
    source: "Hamlet"
  },
  {
    id: "23",
    text: "The unexamined life is not worth living.",
    author: "Socrates",
    date: "-399-01-01",
    topics: ["life", "philosophy"],
    theme: "introspection",
  },
  {
    id: "24",
    text: "The only thing necessary for the triumph of evil is for good men to do nothing.",
    author: "Edmund Burke",
    date: "1770-01-01",
    topics: ["evil", "society"],
    theme: "responsibility",
  },
  {
    id: "25",
    text: "The greatest wealth is to live content with little.",
    author: "Plato",
    date: "-380-01-01",
    topics: ["wealth", "philosophy"],
    theme: "contentment",
  },
  {
    id: "26",
    text: "Where there is love there is life.",
    author: "Mahatma Gandhi",
    date: "1931-01-01",
    topics: ["love", "life"],
    theme: "vitality",
  },
  {
    id: "27",
    text: "We are all in the gutter, but some of us are looking at the stars.",
    author: "Oscar Wilde",
    date: "1897-01-01",
    topics: ["hope", "perspective"],
    theme: "aspiration",
    source: "Lady Windermere's Fan"
  },
  {
    id: "28",
    text: "The truth will set you free, but first it will piss you off.",
    author: "Joe Klaas",
    date: "1994-01-01",
    topics: ["truth", "freedom"],
    theme: "honesty",
  },
  {
    id: "29",
    text: "Not all those who wander are lost.",
    author: "J.R.R. Tolkien",
    date: "1954-01-01",
    topics: ["travel", "individuality"],
    theme: "exploration",
    source: "The Fellowship of the Ring"
  },
  {
    id: "30",
    text: "The best revenge is massive success.",
    author: "Frank Sinatra",
    date: "1964-01-01",
    topics: ["success", "revenge"],
    theme: "achievement",
  },
  {
    id: "31",
    text: "If you can't explain it to a six year old, you don't understand it yourself.",
    author: "Albert Einstein",
    date: "1930-01-01",
    topics: ["understanding", "simplicity"],
    theme: "clarity",
  },
  {
    id: "32",
    text: "I would like to die on Mars. Just not on impact.",
    author: "Elon Musk",
    date: "2015-01-01",
    topics: ["humor", "space"],
    theme: "ambition",
  },
  {
    id: "33",
    text: "The greatest trick the Devil ever pulled was convincing the world he didn't exist.",
    author: "Charles Baudelaire",
    date: "1869-01-01",
    topics: ["evil", "deception"],
    theme: "illusion",
  },
  {
    id: "34",
    text: "The secret of getting ahead is getting started.",
    author: "Mark Twain",
    date: "1883-01-01",
    topics: ["success", "action"],
    theme: "initiative",
  },
  {
    id: "35",
    text: "It is better to be hated for what you are than to be loved for what you are not.",
    author: "André Gide",
    date: "1926-01-01",
    topics: ["individuality", "authenticity"],
    theme: "integrity",
  },
  {
    id: "36",
    text: "The unhappiest people in this world, are those who care the most about what other people think.",
    author: "C. JoyBell C.",
    date: "2011-01-01",
    topics: ["happiness", "society"],
    theme: "independence",
  },
  {
    id: "37",
    text: "A life spent making mistakes is not only more honorable, but more useful, than a life spent doing nothing.",
    author: "George Bernard Shaw",
    date: "1903-01-01",
    topics: ["life", "mistakes"],
    theme: "experience",
  },
  {
    id: "38",
    text: "The most common way people give up their power is by thinking they don't have any.",
    author: "Alice Walker",
    date: "1983-01-01",
    topics: ["power", "society"],
    theme: "empowerment",
  },
  {
    id: "39",
    text: "The best proof of love is trust.",
    author: "Joyce Brothers",
    date: "1988-01-01",
    topics: ["love", "trust"],
    theme: "relationship",
  },
  {
    id: "40",
    text: "The future is already here – it's just not very evenly distributed.",
    author: "William Gibson",
    date: "1993-01-01",
    topics: ["future", "technology"],
    theme: "inequality",
  },
  {
    id: "41",
    text: "Anyone who has never made a mistake has never tried anything new.",
    author: "Albert Einstein",
    date: "1955-01-01",
    topics: ["mistakes", "innovation"],
    theme: "experimentation",
  },
  {
    id: "42",
    text: "I have not failed. I've just found 10,000 ways that won't work.",
    author: "Thomas A. Edison",
    date: "1879-01-01",
    topics: ["failure", "perseverance"],
    theme: "persistence",
  },
  {
    id: "43",
    text: "The mind is not a vessel to be filled, but a fire to be kindled.",
    author: "Plutarch",
    date: "0100-01-01",
    topics: ["mind", "education"],
    theme: "inspiration",
  },
  {
    id: "44",
    text: "What we think, we become.",
    author: "Buddha",
    date: "-500-01-01",
    topics: ["mind", "philosophy"],
    theme: "self-belief",
  },
  {
    id: "45",
    text: "Strive for progress, not perfection.",
    author: "Unknown",
    date: "2020-01-01",
    topics: ["progress", "goals"],
    theme: "improvement",
  },
  {
    id: "46",
    text: "The best time to plant a tree was 20 years ago. The second best time is now.",
    author: "Chinese Proverb",
    date: "0100-01-01",
    topics: ["action", "time"],
    theme: "opportunity",
  },
  {
    id: "47",
    text: "If you want to lift yourself up, lift up someone else.",
    author: "Booker T. Washington",
    date: "1900-01-01",
    topics: ["help", "society"],
    theme: "altruism",
  },
  {
    id: "48",
    text: "The only person you are destined to become is the person you decide to be.",
    author: "Ralph Waldo Emerson",
    date: "1841-01-01",
    topics: ["destiny", "self"],
    theme: "determination",
  },
  {
    id: "49",
    text: "The biggest risk is not taking any risk... In a world that is changing really quickly, the only strategy that is guaranteed to fail is not taking risks.",
    author: "Mark Zuckerberg",
    date: "2011-01-01",
    topics: ["risk", "business"],
    theme: "courage",
  },
  {
    id: "50",
    text: "Everything you’ve ever wanted is on the other side of fear.",
    author: "George Addair",
    date: "1980-01-01",
    topics: ["fear", "goals"],
    theme: "bravery",
  },
  {
    id: "51",
    text: "The most wasted of all days is one without laughter.",
    author: "E.E. Cummings",
    date: "1958-01-01",
    topics: ["laughter", "life"],
    theme: "joy",
  },
  {
    id: "52",
    text: "Do one thing every day that scares you.",
    author: "Eleanor Roosevelt",
    date: "1936-01-01",
    topics: ["fear", "action"],
    theme: "courage",
  },
  {
    id: "53",
    text: "It does not do to dwell on dreams and forget to live.",
    author: "J.K. Rowling",
    date: "2000-01-01",
    topics: ["dreams", "life"],
    theme: "reality",
    source: "Harry Potter and the Sorcerer's Stone"
  },
  {
    id: "54",
    text: "The best view comes after the hardest climb.",
    author: "Unknown",
    date: "2010-01-01",
    topics: ["perseverance", "success"],
    theme: "reward",
  },
  {
    id: "55",
    text: "If you look at what you have in life, you'll always have more. If you look at what you don't have in life, you'll never have enough.",
    author: "Oprah Winfrey",
    date: "2000-01-01",
    topics: ["gratitude", "life"],
    theme: "abundance",
  },
  {
    id: "56",
    text: "Believe you can and you're halfway there.",
    author: "Theodore Roosevelt",
    date: "1900-01-01",
    topics: ["belief", "success"],
    theme: "confidence",
  },
  {
    id: "57",
    text: "May the Force be with you.",
    author: "George Lucas",
    date: "1977-01-01",
    topics: ["hope", "inspiration"],
    theme: "destiny",
    source: "Star Wars: A New Hope"
  },
  {
    id: "58",
    text: "The only way to have a friend is to be one.",
    author: "Ralph Waldo Emerson",
    date: "1841-01-01",
    topics: ["friendship", "relationships"],
    theme: "reciprocity",
  },
  {
    id: "59",
    text: "The greatest glory in living lies not in never falling, but in rising every time we fall.",
    author: "Nelson Mandela",
    date: "2000-01-01",
    topics: ["perseverance", "life"],
    theme: "resilience",
  },
  {
    id: "60",
    text: "Keep your eyes on the stars, and your feet on the ground.",
    author: "Theodore Roosevelt",
    date: "1900-01-01",
    topics: ["goals", "reality"],
    theme: "balance",
  },
  {
    id: "61",
    text: "The best and most beautiful things in the world cannot be seen or even touched - they must be felt with the heart.",
    author: "Helen Keller",
    date: "1920-01-01",
    topics: ["beauty", "emotion"],
    theme: "perception",
  },
  {
    id: "62",
    text: "It is never too late to be what you might have been.",
    author: "George Eliot",
    date: "1872-01-01",
    topics: ["potential", "self"],
    theme: "opportunity",
  },
  {
    id: "63",
    text: "The only thing we have to fear is fear itself.",
    author: "Franklin D. Roosevelt",
    date: "1933-01-01",
    topics: ["fear", "courage"],
    theme: "overcoming",
  },
  {
    id: "64",
    text: "To handle yourself, use your head; to handle others, use your heart.",
    author: "Eleanor Roosevelt",
    date: "1933-01-01",
    topics: ["leadership", "relationships"],
    theme: "compassion",
  },
  {
    id: "65",
    text: "The future belongs to those who believe in the beauty of their dreams.",
    author: "Eleanor Roosevelt",
    date: "1933-01-01",
    topics: ["dreams", "future"],
    theme: "hope",
  },
  {
    id: "66",
    text: "The only limit to our realization of tomorrow will be our doubts of today.",
    author: "Franklin D. Roosevelt",
    date: "1939-01-01",
    topics: ["future", "belief"],
    theme: "optimism",
  },
  {
    id: "67",
    text: "The journey of a thousand miles begins with a single step.",
    author: "Lao Tzu",
    date: "-600-01-01",
    topics: ["perseverance", "goals"],
    theme: "initiation",
  },
  {
    id: "68",
    text: "Life is what happens when you're busy making other plans.",
    author: "John Lennon",
    date: "1980-01-01",
    topics: ["life", "perspective"],
    theme: "spontaneity",
  },
  {
    id: "69",
    text: "The greatest glory in living lies not in never falling, but in rising every time we fall.",
    author: "Nelson Mandela",
    date: "2000-01-01",
    topics: ["perseverance", "life"],
    theme: "resilience",
  },
  {
    id: "70",
    text: "Do not go where the path may lead, go instead where there is no path and leave a trail.",
    author: "Ralph Waldo Emerson",
    date: "1841-01-01",
    topics: ["leadership", "individuality"],
    theme: "innovation",
  },
  {
    id: "71",
    text: "The best way to predict the future is to create it.",
    author: "Peter Drucker",
    date: "1963-01-01",
    topics: ["future", "innovation"],
    theme: "proactivity",
  },
  {
    id: "72",
    text: "Happiness is not something readymade. It comes from your own actions.",
    author: "Dalai Lama",
    date: "1998-01-01",
    topics: ["happiness", "philosophy"],
    theme: "mindfulness",
  },
   {
    id: "73",
    text: "The only true wisdom is in knowing you know nothing.",
    author: "Socrates",
    date: "-399-01-01",
    topics: ["wisdom", "philosophy"],
    theme: "humility",
  },
  {
    id: "74",
    text: "I have always depended on the kindness of strangers.",
    author: "Tennessee Williams",
    date: "1947-01-01",
    topics: ["kindness", "society"],
    theme: "vulnerability",
    source: "A Streetcar Named Desire"
  },
  {
    id: "75",
    text: "That it will never come again is what makes life so sweet.",
    author: "Emily Dickinson",
    date: "1864-01-01",
    topics: ["life", "perspective"],
    theme: "transience",
  },
  {
    id: "76",
    text: "Don't cry because it's over, smile because it happened.",
    author: "Dr. Seuss",
    date: "1956-01-01",
    topics: ["life", "happiness"],
    theme: "gratitude",
  },
  {
    id: "77",
    text: "To be or not to be, that is the question.",
    author: "William Shakespeare",
    date: "1603-01-01",
    topics: ["life", "philosophy"],
    theme: "existence",
    source: "Hamlet"
  },
  {
    id: "78",
    text: "The unexamined life is not worth living.",
    author: "Socrates",
    date: "-399-01-01",
    topics: ["life", "philosophy"],
    theme: "introspection",
  },
  {
    id: "79",
    text: "The only thing necessary for the triumph of evil is for good men to do nothing.",
    author: "Edmund Burke",
    date: "1770-01-01",
    topics: ["evil", "society"],
    theme: "responsibility",
  },
  {
    id: "80",
    text: "The greatest wealth is to live content with little.",
    author: "Plato",
    date: "-380-01-01",
    topics: ["wealth", "philosophy"],
    theme: "contentment",
  },
  {
    id: "81",
    text: "Where there is love there is life.",
    author: "Mahatma Gandhi",
    date: "1931-01-01",
    topics: ["love", "life"],
    theme: "vitality",
  },
  {
    id: "82",
    text: "We are all in the gutter, but some of us are looking at the stars.",
    author: "Oscar Wilde",
    date: "1897-01-01",
    topics: ["hope", "perspective"],
    theme: "aspiration",
    source: "Lady Windermere's Fan"
  },
  {
    id: "83",
    text: "The truth will set you free, but first it will piss you off.",
    author: "Joe Klaas",
    date: "1994-01-01",
    topics: ["truth", "freedom"],
    theme: "honesty",
  },
  {
    id: "84",
    text: "Not all those who wander are lost.",
    author: "J.R.R. Tolkien",
    date: "1954-01-01",
    topics: ["travel", "individuality"],
    theme: "exploration",
    source: "The Fellowship of the Ring"
  },
  {
    id: "85",
    text: "The best revenge is massive success.",
    author: "Frank Sinatra",
    date: "1964-01-01",
    topics: ["success", "revenge"],
    theme: "achievement",
  },
  {
    id: "86",
    text: "If you can't explain it to a six year old, you don't understand it yourself.",
    author: "Albert Einstein",
    date: "1930-01-01",
    topics: ["understanding", "simplicity"],
    theme: "clarity",
  },
  {
    id: "87",
    text: "I would like to die on Mars. Just not on impact.",
    author: "Elon Musk",
    date: "2015-01-01",
    topics: ["humor", "space"],
    theme: "ambition",
  },
  {
    id: "88",
    text: "The greatest trick the Devil ever pulled was convincing the world he didn't exist.",
    author: "Charles Baudelaire",
    date: "1869-01-01",
    topics: ["evil", "deception"],
    theme: "illusion",
  },
  {
    id: "89",
    text: "The secret of getting ahead is getting started.",
    author: "Mark Twain",
    date: "1883-01-01",
    topics: ["success", "action"],
    theme: "initiative",
  },
  {
    id: "90",
    text: "It is better to be hated for what you are than to be loved for what you are not.",
    author: "André Gide",
    date: "1926-01-01",
    topics: ["individuality", "authenticity"],
    theme: "integrity",
  },
  {
    id: "91",
    text: "The unhappiest people in this world, are those who care the most about what other people think.",
    author: "C. JoyBell C.",
    date: "2011-01-01",
    topics: ["happiness", "society"],
    theme: "independence",
  },
  {
    id: "92",
    text: "A life spent making mistakes is not only more honorable, but more useful, than a life spent doing nothing.",
    author: "George Bernard Shaw",
    date: "1903-01-01",
    topics: ["life", "mistakes"],
    theme: "experience",
  },
  {
    id: "93",
    text: "The most common way people give up their power is by thinking they don't have any.",
    author: "Alice Walker",
    date: "1983-01-01",
    topics: ["power", "society"],
    theme: "empowerment",
  },
  {
    id: "94",
    text: "The best proof of love is trust.",
    author: "Joyce Brothers",
    date: "1988-01-01",
    topics: ["love", "trust"],
    theme: "relationship",
  },
  {
    id: "95",
    text: "The future is already here – it's just not very evenly distributed.",
    author: "William Gibson",
    date: "1993-01-01",
    topics: ["future", "technology"],
    theme: "inequality",
  },
  {
    id: "96",
    text: "Anyone who has never made a mistake has never tried anything new.",
    author: "Albert Einstein",
    date: "1955-01-01",
    topics: ["mistakes", "innovation"],
    theme: "experimentation",
  },
  {
    id: "97",
    text: "I have not failed. I've just found 10,000 ways that won't work.",
    author: "Thomas A. Edison",
    date: "1879-01-01",
    topics: ["failure", "perseverance"],
    theme: "persistence",
  },
  {
    id: "98",
    text: "The mind is not a vessel to be filled, but a fire to be kindled.",
    author: "Plutarch",
    date: "0100-01-01",
    topics: ["mind", "education"],
    theme: "inspiration",
  },
  {
    id: "99",
    text: "What we think, we become.",
    author: "Buddha",
    date: "-500-01-01",
    topics: ["mind", "philosophy"],
    theme: "self-belief",
  },
  {
    id: "100",
    text: "Strive for progress, not perfection.",
    author: "Unknown",
    date: "2020-01-01",
    topics: ["progress", "goals"],
    theme: "improvement",
  },
  {
    id: "101",
    text: "The best time to plant a tree was 20 years ago. The second best time is now.",
    author: "Chinese Proverb",
    date: "0100-01-01",
    topics: ["action", "time"],
    theme: "opportunity",
  },
  {
    id: "102",
    text: "If you want to lift yourself up, lift up someone else.",
    author: "Booker T. Washington",
    date: "1900-01-01",
    topics: ["help", "society"],
    theme: "altruism",
  },
  {
    id: "103",
    text: "The only person you are destined to become is the person you decide to be.",
    author: "Ralph Waldo Emerson",
    date: "1841-01-01",
    topics: ["destiny", "self"],
    theme: "determination",
  },
  {
    id: "104",
    text: "The biggest risk is not taking any risk... In a world that is changing really quickly, the only strategy that is guaranteed to fail is not taking risks.",
    author: "Mark Zuckerberg",
    date: "2011-01-01",
    topics: ["risk", "business"],
    theme: "courage"
  }
];
