export interface Quote {
  id: string,
  text: string,
  author: string,
  date: string,
  topics: string[],
  theme: string,
  source?: string,
  evidenceImage?: string,
  sourceUrl?: string,
  sourcePublicationDate?: string,
  originalLanguage?: string,
  originalText?: string,
  context?: string,
  historicalContext?: string,
  keywords?: string[],
  citationAPA?: string,
  citationMLA?: string,
  citationChicago?: string,
  exportFormats?: {
    json?: boolean,
    csv?: boolean,
    cff?: boolean
  },
  shareCount?: number,
  variations?: any[],
  crossReferencedQuotes?: any[],
  ocrExtractedText?: string,
  ocrConfidenceScore?: number,
  originalManuscriptReference?: string,
  attributionStatus?: string,
  translator?: string,
  impact?: string,
  citedBy?: {
    siteName: string,
    siteUrl: string,
    embedDate: string
  }[],
  translations?: {
    fr?: {
      text: string,
      source?: string
    }
  }
}

export const quotes: Quote[] = [
  {
    id: "1",
    text: "The only way to do great work is to love what you do.",
    author: "Steve Jobs",
    date: "2005-06-12",
    topics: ["business", "success"],
    theme: "passion",
    source: "Stanford Commencement Address",
    evidenceImage: "/lovable-uploads/88d0b22b-76de-4abd-87c3-70f960a4d252.png",
    sourceUrl: "https://news.stanford.edu/2005/06/14/jobs-061505/",
    sourcePublicationDate: "2005-06-14",
    context: "Jobs delivered this line during his Stanford commencement address, encouraging graduates to find work they're passionate about.",
    historicalContext: "At the time of this speech, Jobs had recently recovered from his first cancer diagnosis and was reflecting on mortality and meaningful work.",
    attributionStatus: "Confirmed",
    impact: "This quote has become one of Jobs' most cited sayings, inspiring countless entrepreneurs and professionals to pursue careers aligned with their passions.",
    citationAPA: "Jobs, S. (2005, June 12). Stanford University Commencement Address.",
    citationMLA: "Jobs, Steve. \"Stanford University Commencement Address.\" Stanford University, 12 June 2005.",
    citationChicago: "Jobs, Steve. \"Stanford University Commencement Address.\" Speech, Stanford, CA, June 12, 2005.",
    ocrExtractedText: "The only way to do great work is to love what you do. If you haven't found it yet, keep looking. Don't settle.",
    ocrConfidenceScore: 0.98,
    citedBy: [
      {
        siteName: "Forbes",
        siteUrl: "https://www.forbes.com/sites/forbesleadershipforum/2013/05/13/steve-jobs-best-quotes-for-entrepreneurs/",
        embedDate: "2013-05-13"
      },
      {
        siteName: "Harvard Business Review",
        siteUrl: "https://hbr.org/2011/10/steve-jobss-ultimate-lesson-fo",
        embedDate: "2011-10-07"
      }
    ]
  },
  {
    id: "2",
    text: "Innovation distinguishes between a leader and a follower.",
    author: "Steve Jobs",
    date: "1996-01-01",
    topics: ["business", "innovation"],
    theme: "leadership",
  },
  {
    id: "3",
    text: "The future belongs to those who believe in the beauty of their dreams.",
    author: "Eleanor Roosevelt",
    date: "1933-01-01",
    topics: ["inspirational", "dreams"],
    theme: "hope",
  },
  {
    id: "4",
    text: "The best and most beautiful things in the world cannot be seen or even touched - they must be felt with the heart.",
    author: "Helen Keller",
    date: "1920-01-01",
    topics: ["love", "beauty"],
    theme: "emotion",
  },
  {
    id: "5",
    text: "Strive not to be a success, but rather to be of value.",
    author: "Albert Einstein",
    date: "1949-01-01",
    topics: ["success", "value"],
    theme: "purpose",
  },
  {
    id: "6",
    text: "The mind is everything. What you think you become.",
    author: "Buddha",
    date: "-500-01-01",
    topics: ["mind", "philosophy"],
    theme: "mindset",
  },
  {
    id: "7",
    text: "Two things are infinite: the universe and human stupidity; and I'm not sure about the universe.",
    author: "Albert Einstein",
    date: "1922-01-01",
    topics: ["humor", "science"],
    theme: "humor",
  },
  {
    id: "8",
    text: "Be the change that you wish to see in the world.",
    author: "Mahatma Gandhi",
    date: "1913-01-01",
    topics: ["change", "inspirational"],
    theme: "activism",
  },
  {
    id: "9",
    text: "Darkness cannot drive out darkness: only light can do that. Hate cannot drive out hate: only love can do that.",
    author: "Martin Luther King Jr.",
    date: "1963-01-01",
    topics: ["love", "peace"],
    theme: "unity",
  },
  {
    id: "10",
    text: "The only limit to our realization of tomorrow will be our doubts of today.",
    author: "Franklin D. Roosevelt",
    date: "1939-01-01",
    topics: ["future", "inspirational"],
    theme: "optimism",
  },
  {
    id: "11",
    text: "It is our choices, Harry, that show what we truly are, far more than our abilities.",
    author: "J.K. Rowling",
    date: "1999-01-01",
    topics: ["choices", "character"],
    theme: "integrity",
    source: "Harry Potter and the Chamber of Secrets"
  },
  {
    id: "12",
    text: "The journey of a thousand miles begins with one step.",
    author: "Lao Tzu",
    date: "-0600-01-01",
    topics: ["inspirational", "perseverance"],
    theme: "determination",
  },
  {
    id: "13",
    text: "Life is what happens when you're busy making other plans.",
    author: "John Lennon",
    date: "1980-01-01",
    topics: ["life", "perspective"],
    theme: "reality",
  },
  {
    id: "14",
    text: "The greatest glory in living lies not in never falling, but in rising every time we fall.",
    author: "Nelson Mandela",
    date: "2000-01-01",
    topics: ["inspirational", "perseverance"],
    theme: "resilience",
  },
  {
    id: "15",
    text: "Do not go where the path may lead, go instead where there is no path and leave a trail.",
    author: "Ralph Waldo Emerson",
    date: "1841-01-01",
    topics: ["leadership", "individuality"],
    theme: "innovation",
  },
  {
    id: "16",
    text: "The best way to predict the future is to create it.",
    author: "Peter Drucker",
    date: "1963-01-01",
    topics: ["future", "innovation"],
    theme: "proactivity",
  },
  {
    id: "17",
    text: "Happiness is not something readymade. It comes from your own actions.",
    author: "Dalai Lama",
    date: "1998-01-01",
    topics: ["happiness", "philosophy"],
    theme: "mindfulness",
  },
  {
    id: "18",
    text: "The only true wisdom is in knowing you know nothing.",
    author: "Socrates",
    date: "-399-01-01",
    topics: ["wisdom", "philosophy"],
    theme: "humility",
  },
  {
    id: "19",
    text: "I have always depended on the kindness of strangers.",
    author: "Tennessee Williams",
    date: "1947-01-01",
    topics: ["kindness", "society"],
    theme: "vulnerability",
    source: "A Streetcar Named Desire"
  },
  {
    id: "20",
    text: "That it will never come again is what makes life so sweet.",
    author: "Emily Dickinson",
    date: "1864-01-01",
    topics: ["life", "perspective"],
    theme: "transience",
  },
  {
    id: "21",
    text: "Don't cry because it's over, smile because it happened.",
    author: "Dr. Seuss",
    date: "1956-01-01",
    topics: ["life", "happiness"],
    theme: "gratitude",
  },
  {
    id: "22",
    text: "To be or not to be, that is the question.",
    author: "William Shakespeare",
    date: "1603-01-01",
    topics: ["life", "philosophy"],
    theme: "existence",
    source: "Hamlet"
  },
  {
    id: "23",
    text: "The unexamined life is not worth living.",
    author: "Socrates",
    date: "-399-01-01",
    topics: ["life", "philosophy"],
    theme: "introspection",
  },
  {
    id: "24",
    text: "The only thing necessary for the triumph of evil is for good men to do nothing.",
    author: "Edmund Burke",
    date: "1770-01-01",
    topics: ["evil", "society"],
    theme: "responsibility",
  },
  {
    id: "25",
    text: "The greatest wealth is to live content with little.",
    author: "Plato",
    date: "-380-01-01",
    topics: ["wealth", "philosophy"],
    theme: "contentment",
  },
  {
    id: "26",
    text: "Where there is love there is life.",
    author: "Mahatma Gandhi",
    date: "1931-01-01",
    topics: ["love", "life"],
    theme: "vitality",
  },
  {
    id: "27",
    text: "We are all in the gutter, but some of us are looking at the stars.",
    author: "Oscar Wilde",
    date: "1897-01-01",
    topics: ["hope", "perspective"],
    theme: "aspiration",
    source: "Lady Windermere's Fan"
  },
  {
    id: "28",
    text: "The truth will set you free, but first it will piss you off.",
    author: "Joe Klaas",
    date: "1994-01-01",
    topics: ["truth", "freedom"],
    theme: "honesty",
  },
  {
    id: "29",
    text: "Not all those who wander are lost.",
    author: "J.R.R. Tolkien",
    date: "1954-01-01",
    topics: ["travel", "individuality"],
    theme: "exploration",
    source: "The Fellowship of the Ring"
  },
  {
    id: "30",
    text: "The best revenge is massive success.",
    author: "Frank Sinatra",
    date: "1964-01-01",
    topics: ["success", "revenge"],
    theme: "achievement",
  },
  {
    id: "31",
    text: "If you can't explain it to a six year old, you don't understand it yourself.",
    author: "Albert Einstein",
    date: "1930-01-01",
    topics: ["understanding", "simplicity"],
    theme: "clarity",
  },
  {
    id: "32",
    text: "I would like to die on Mars. Just not on impact.",
    author: "Elon Musk",
    date: "2015-01-01",
    topics: ["humor", "space"],
    theme: "ambition",
  },
  {
    id: "33",
    text: "Without freedom of the press, there can be no representative government.",
    author: "Thomas Jefferson",
    date: "1823-11-07",
    topics: ["freedom", "government"],
    theme: "democracy",
    source: "Letter to Lafayette",
    evidenceImage: "/lovable-uploads/9fe7c698-558b-4981-a5fa-73e7bb8ea87f.png",
    sourceUrl: "https://founders.archives.gov/documents/Jefferson/98-01-02-3843",
    sourcePublicationDate: "1823-11-07",
    attributionStatus: "Confirmed",
    citationAPA: "Jefferson, T. (1823, November 7). Letter to Lafayette.",
    citationMLA: "Jefferson, Thomas. \"Letter to Lafayette.\" 7 Nov. 1823.",
    citationChicago: "Jefferson, Thomas. Letter to Lafayette, November 7, 1823.",
    ocrExtractedText: "Without freedom of the press, there can be no representative government, nor any other permanent free government.",
    ocrConfidenceScore: 0.96,
    historicalContext: "Jefferson wrote this in the context of the emerging democratic republics in Latin America, where he emphasized the critical importance of press freedom for democratic governance.",
    impact: "This quote became a foundational principle for American press freedom and has been cited in numerous Supreme Court cases on First Amendment rights."
  },
  {
    id: "34",
    text: "La vie n'est pas ce qu'on a vécu, mais ce dont on se souvient et comment on s'en souvient.",
    author: "Gabriel García Márquez",
    date: "2002-07-05",
    topics: ["memory", "life"],
    theme: "perspective",
    source: "Vivre pour la raconter",
    originalLanguage: "Spanish",
    originalText: "La vida no es la que uno vivió, sino la que uno recuerda y cómo la recuerda para contarla.",
    translator: "Claude Couffon",
    attributionStatus: "Confirmed",
    translations: {
      fr: {
        text: "La vie n'est pas ce qu'on a vécu, mais ce dont on se souvient et comment on s'en souvient.",
        source: "Vivre pour la raconter"
      }
    }
  },
  {
    id: "35",
    text: "An unjust law is itself a species of violence. Arrest for its breach is more so.",
    author: "Mahatma Gandhi",
    date: "1930-03-02",
    topics: ["justice", "civil disobedience"],
    theme: "resistance",
    source: "Young India",
    evidenceImage: "/lovable-uploads/7f15ed9e-c194-44df-a54d-54f0d2bfef77.png",
    sourceUrl: "https://www.mkgandhi.org/youngindi/index.htm",
    sourcePublicationDate: "1930-03-02",
    attributionStatus: "Confirmed",
    citationAPA: "Gandhi, M. (1930, March 2). Young India.",
    citationMLA: "Gandhi, Mahatma. \"Young India.\" 2 Mar. 1930.",
    citationChicago: "Gandhi, Mahatma. Young India, March 2, 1930.",
    historicalContext: "Gandhi wrote this during the Salt Satyagraha (Salt March), a nonviolent protest against British salt monopoly and taxation in colonial India.",
    impact: "This quote became a cornerstone of nonviolent civil disobedience movements worldwide, including the American Civil Rights Movement led by Martin Luther King Jr."
  },
  {
    id: "36",
    text: "There is but one truly serious philosophical question, and that is suicide.",
    author: "Albert Camus",
    date: "1941-12-31",
    topics: ["philosophy", "existentialism"],
    theme: "absurdism",
    source: "The Myth of Sisyphus",
    originalLanguage: "French",
    originalText: "Il n'y a qu'un problème philosophique vraiment sérieux: c'est le suicide.",
    translator: "Justin O'Brien",
    attributionStatus: "Confirmed",
    translations: {
      fr: {
        text: "Il n'y a qu'un problème philosophique vraiment sérieux: c'est le suicide.",
        source: "Le Mythe de Sisyphe"
      }
    }
  }
]
